services:
  etherpad1:
    image: etherpad/etherpad
    container_name: etherpad1
    ports:
      - "9001:9001"
    volumes:
      - "./support/settings.json:/opt/etherpad-lite/settings.json"
      - "./test1:/opt/etherpad-lite/var"
  etherpad2:
    image: etherpad/etherpad
    container_name: etherpad2
    ports:
      - "9002:9001"
    volumes:
      - "./support/settings.json:/opt/etherpad-lite/settings.json"
      - "./test2:/opt/etherpad-lite/var"
  etherpad3:
    container_name: etherpad3
    image: etherpad/etherpad
    ports:
      - "9003:9001"
    volumes:
      - "./support/settings.json:/opt/etherpad-lite/settings.json"
      - "./test3:/opt/etherpad-lite/var"
  reverse-proxy:
    container_name: reverse-proxy
    image: ghcr.io/ether/etherpad-proxy:latest
    ports:
      - "9000:9000"
    volumes:
      - ./reverse-proxy/db:/app/db
      - ./settings.json:/app/settings.json