name: "Proxy Test"

# any branch is useful for testing before a PR is submitted
on: [push, pull_request]

jobs:
  deployAndLoadTest:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
         (github.event_name != 'pull_request')
         || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: Something..
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 15

    - name: install dependencies
      run: npm i

      # install and run etherpad twice on 9001 and 9002
    - name: Git clone etherpad to test1
      run: git clone https://github.com/ether/etherpad-lite.git test1

    - name: start etherpad >> test1
      run: cd test1 && cd src && npm i --no-optional && node ../../../node/server.js &

    - name: Git clone etherpad to test2
      run: cd .. && cd .. && git clone https://github.com/ether/etherpad-lite.git test2

    - name: Enter in test2
      run: cd test2

      # name: Change port to 9002
      # run: powershell -Command "(gc settings.json.template) -replace '\"port\": 9001', '\"port\": 9002' | Out-File -encoding ASCII settings.json"

    - name: start etherpad >> test2
      run: cd src && npm i --no-optional && node ../../../node/server.js &

    - name: return to root
      run: cd ..

    - name: Start proxy
      run: node app.js &

    - name: Install etherpad-load-test
      run: npm install etherpad-load-test -g

    - name: Load test >> test1
      run: etherpad-loadtest http://localhost:9000/p/test1 -d 60 &

    - name: Load test >> test2
      run: etherpad-loadtest http://localhost:9000/p/test2 -d 60 &

    - name: check test1
      run: dir test1/var/dirty.db

    - name: check test2
      run: dir test2/var/dirty.db
