name: "Proxy Test"

# any branch is useful for testing before a PR is submitted
on: [push, pull_request]

jobs:
  deployAndLoadTest:
    # run on pushes to any branch
    # run on PRs from external forks
    if: |
         (github.event_name != 'pull_request')
         || (github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id)
    name: Connections are proxied to different backends
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 15

    - name: install dependencies
      run: npm i

      # install and run etherpad twice on 9001 and 9002
    - name: Git clone etherpad to test1
      run: git clone https://github.com/ether/etherpad-lite.git test1

    - name: prep etherpad >> test1
      run: cd test1/src && npm i --no-optional

    - name: start etherpad >> test1
      run: cd test1 && node src/node/server.js &

    - name: Git clone etherpad to test2
      run: git clone https://github.com/ether/etherpad-lite.git test2

    - name: Change port to 9002
      # "port" : 9001 >> "port" :9002
      run: sed 's/9001/9002/g' test2/settings.json.template > test2/settings.json

    - name: prep etherpad >> test2
      run: cd test2/src && npm i --no-optional

    - name: start etherpad >> test2
      run: cd test2 && node src/node/server.js &

    - name: Start proxy
      run: node app.js &

    - name: Install etherpad-load-test
      run: npm install etherpad-load-test -g

    - name: Wait For test2 instance to start
      uses: nev7n/wait_for_response@v1
      with:
        url: 'http://localhost:9002/'
        timeout: 60000
        interval: 1000

    - name: Load test >> test1
      run: etherpad-loadtest http://localhost:9000/p/test1 -d 60 &

    - name: Sleep for 10 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'

    - name: Load test >> test2
      run: etherpad-loadtest http://localhost:9000/p/test2 -d 60 &

    - name: check test1
      run: test $( wc -l < test1/var/dirty.db ) -lt 2500

    - name: check test2
      run: test $( wc -l < test2/var/dirty.db ) -lt 2500
