name: 'Build etherpad-proxy'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 'Build app with cargo'
        run: RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release
      - uses: actions/upload-artifact@v4
        with:
          name: 'etherpad-proxy'
          path: './target/x86_64-unknown-linux-gnu/release/etherpad-proxy'
  deployAndLoadTest:
    runs-on: ubuntu-latest
    needs: build
    services:
      etherpad1:
        image: etherpad/etherpad:develop
        ports:
          - "9001:9001"
        volumes:
          - "./support/settings.json:/opt/etherpad-lite/settings.json"
          - "./test1:/opt/etherpad-lite/var"
      etherpad2:
        image: etherpad/etherpad:develop
        ports:
          - "9002:9001"
        volumes:
          - "./support/settings.json:/opt/etherpad-lite/settings.json"
          - "./test2:/opt/etherpad-lite/var"
      etherpad3:
        image: etherpad/etherpad:develop
        ports:
          - "9003:9001"
        volumes:
          - "./support/settings.json:/opt/etherpad-lite/settings.json"
          - "./test3:/opt/etherpad-lite/var"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: 'etherpad-proxy'
      - name: support 1 pad per instances
        run: sed 's/5/1/g' settings.json.template > settings.json
      - name: check settings
        run: cat settings.json
      - name: Start proxy
        run: ./etherpad-proxy &
      - name: Install etherpad-load-test
        run: npm install etherpad-load-test -g
      - name: wait for Etherpad
        run: curl --connect-timeout 10 --max-time 20 --retry 5 --retry-delay 10 --retry-max-time 60 --retry-connrefused http://127.0.0.1:9003/p/test
      - name: Load test >> test1
        run: etherpad-loadtest http://localhost:9000/p/test1 -d 60 &
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Load test >> test2
        run: etherpad-loadtest http://localhost:9000/p/test2 -d 60 &
      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Load test >> test3
        run: etherpad-loadtest http://localhost:9000/p/test3 -d 60 &