name: 'Build etherpad-proxy'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 'Build app with cargo'
        run: RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release
      - uses: actions/upload-artifact@v4
        with:
          name: 'etherpad-proxy'
          path: './target/x86_64-unknown-linux-gnu/release/etherpad-proxy'
  deployAndLoadTest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: 'etherpad-proxy'
