name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 6 * * *'
permissions:
  issues: write
  pull-requests: write
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          exempt-issue-labels:
            - pinned
            - security
            - Bug
            - Serious Bug
            - Minor bug
            - Black hole bug
            - Special case Bug
            - Upstream bug
          exempt-pr-labels:
            - pinned
            - security
            - Bug
            - Serious Bug
            - Minor bug
            - Black hole bug
            - Special case Bug
            - Upstream bug
          stale-issue-label: wontfix
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not
            had recent activity. It will be closed if no further activity
            occurs. Thank you for your contributions.
          stale-pr-label: wontfix
          stale-pr-message: >
            This pull request has been automatically marked as stale because it
            has not had recent activity. It will be closed if no further
            activity occurs. Thank you for your contributions.
